---

- hosts: all
  become: true
  gather_facts: false

  vars_prompt:
    - name: remove_package
      prompt: "Nama Package Yang Akan di Remove"
      private: no

  tasks:
    - name: Remove {{ remove_package }} package
      package:
        name: "{{ remove_package }}"
        state: absent

