---

- hosts: all
  become: true
  gather_facts: false
  
  tasks:

  - name: install all update server
    package:
      update_only: yes
      update_cache: yes
    tags: always 

- hosts: webserver
  become: true

  tasks:

  - name: install web server http centos
    package: 
      name: httpd
      state: latest
    
  - name: start and enable webserver
    ansible.builtin.service:
      enabled: true
      name: httpd
      state: started
    tags: install_and_enabled_httpd

  - name: copy web package to server
    tags: copy_file
    copy:
      src: ~/Documents/ansible-course/files/ 
      dest: /var/www/html/
      owner: root
      group: root
      mode: 0755

- hosts: database
  become: true

  tasks: 

  - name: install mariadb database package
    package: 
      name: mariadb
      state: latest
    tags: install_mariadb





