- name: install mariadb server (CentOS)
  yum:
    name:
      - "{{ mariadb_package }}"
      - unzip
    state: latest
  tags: mariadb

- name: install terraform for CentOS
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.1.2/terraform_1.1.2_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    owner: root
    group: root
  tags: terraform
 
